"""Servizio di generazione regole Sigma.

Genera regole Sigma YAML per il rilevamento di minacce nei SIEM
a partire da IoC e tecniche di attacco estratte dall'analisi AI.
"""

from __future__ import annotations

import logging
from datetime import datetime
from typing import Any

import yaml

from app.models.schemas import ArticleAnalyzed, SeverityLevel

logger = logging.getLogger(__name__)

# Mappatura severity → Sigma level
SIGMA_LEVEL_MAP = {
    SeverityLevel.CRITICAL: "critical",
    SeverityLevel.HIGH: "high",
    SeverityLevel.MEDIUM: "medium",
    SeverityLevel.LOW: "low",
    SeverityLevel.INFORMATIONAL: "informational",
}


class SigmaService:
    """Genera regole Sigma da articoli analizzati."""

    def generate_sigma_rules(self, article: ArticleAnalyzed) -> str:
        """Genera regole Sigma YAML da un articolo analizzato."""
        if not article.analysis:
            return "# No analysis available for Sigma rule generation"

        analysis = article.analysis
        rules = []

        # Network indicators (IP, domain)
        network_iocs = [
            ioc for ioc in analysis.indicators
            if ioc.type in ("ip", "ipv4", "ipv6", "domain")
        ]
        if network_iocs:
            rules.append(self._generate_network_rule(article, network_iocs))

        # Hash indicators
        hash_iocs = [
            ioc for ioc in analysis.indicators
            if ioc.type in ("hash_md5", "hash_sha1", "hash_sha256")
        ]
        if hash_iocs:
            rules.append(self._generate_hash_rule(article, hash_iocs))

        # URL indicators
        url_iocs = [
            ioc for ioc in analysis.indicators
            if ioc.type == "url"
        ]
        if url_iocs:
            rules.append(self._generate_url_rule(article, url_iocs))

        # DNS query indicators (domains)
        domain_iocs = [
            ioc for ioc in analysis.indicators
            if ioc.type == "domain"
        ]
        if domain_iocs:
            rules.append(self._generate_dns_rule(article, domain_iocs))

        if not rules:
            return f"# No IoCs suitable for Sigma rule generation from: {article.title}"

        header = (
            f"# Sigma Rules generated by CTI Feed RSS Analyzer\n"
            f"# Source: {article.title}\n"
            f"# Date: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}\n"
            f"# Article ID: {article.id}\n\n"
        )
        return header + "\n---\n\n".join(rules)

    def _build_tags(self, article: ArticleAnalyzed) -> list[str]:
        """Genera i tag Sigma dalla analysis."""
        tags = []
        if article.analysis:
            for tech in article.analysis.attack_techniques:
                tid = tech.technique_id.lower().replace(".", "_")
                tags.append(f"attack.{tid}")
                if tech.tactic:
                    tactic_tag = tech.tactic.lower().replace(" ", "_").replace("-", "_")
                    tags.append(f"attack.{tactic_tag}")
        return list(dict.fromkeys(tags))  # deduplicate preserving order

    def _build_base_rule(self, article: ArticleAnalyzed, title_suffix: str) -> dict[str, Any]:
        """Costruisce la struttura base di una regola Sigma."""
        analysis = article.analysis
        level = SIGMA_LEVEL_MAP.get(analysis.severity, "medium") if analysis else "medium"

        rule: dict[str, Any] = {
            "title": f"CTI - {article.title[:100]} - {title_suffix}",
            "id": f"cti-{article.id}-{title_suffix.lower().replace(' ', '-')}",
            "status": "experimental",
            "description": (analysis.summary_en or analysis.summary_it or article.title)[:500] if analysis else article.title,
            "references": [article.link],
            "author": "CTI Feed RSS Analyzer",
            "date": datetime.utcnow().strftime("%Y/%m/%d"),
            "tags": self._build_tags(article),
            "level": level,
            "falsepositives": ["Unknown"],
        }

        if analysis and analysis.threat_actors:
            actors = [ta.name for ta in analysis.threat_actors]
            rule["description"] += f" | Threat Actors: {', '.join(actors)}"

        return rule

    def _generate_network_rule(self, article: ArticleAnalyzed, iocs: list) -> str:
        """Genera una regola Sigma per indicatori di rete (IP)."""
        rule = self._build_base_rule(article, "Network IoC")

        ips = [ioc.value for ioc in iocs if ioc.type in ("ip", "ipv4", "ipv6")]
        domains = [ioc.value for ioc in iocs if ioc.type == "domain"]

        detection: dict[str, Any] = {}
        conditions = []

        if ips:
            detection["selection_ip"] = {
                "DestinationIp|contains": ips
            }
            conditions.append("selection_ip")

        if domains:
            detection["selection_domain"] = {
                "DestinationHostname|contains": domains
            }
            conditions.append("selection_domain")

        detection["condition"] = " or ".join(conditions) if conditions else "selection_ip"

        rule["logsource"] = {
            "category": "firewall",
        }
        rule["detection"] = detection

        return yaml.dump(rule, default_flow_style=False, allow_unicode=True, sort_keys=False)

    def _generate_hash_rule(self, article: ArticleAnalyzed, iocs: list) -> str:
        """Genera una regola Sigma per hash di file."""
        rule = self._build_base_rule(article, "File Hash")

        hashes = [ioc.value.lower() for ioc in iocs]

        rule["logsource"] = {
            "category": "process_creation",
            "product": "windows",
        }
        rule["detection"] = {
            "selection": {
                "Hashes|contains": hashes,
            },
            "condition": "selection",
        }

        return yaml.dump(rule, default_flow_style=False, allow_unicode=True, sort_keys=False)

    def _generate_url_rule(self, article: ArticleAnalyzed, iocs: list) -> str:
        """Genera una regola Sigma per URL malevoli."""
        rule = self._build_base_rule(article, "Malicious URL")

        urls = [ioc.value for ioc in iocs]

        rule["logsource"] = {
            "category": "proxy",
        }
        rule["detection"] = {
            "selection": {
                "c-uri|contains": urls,
            },
            "condition": "selection",
        }

        return yaml.dump(rule, default_flow_style=False, allow_unicode=True, sort_keys=False)

    def _generate_dns_rule(self, article: ArticleAnalyzed, iocs: list) -> str:
        """Genera una regola Sigma per query DNS malevole."""
        rule = self._build_base_rule(article, "DNS Query")

        domains = [ioc.value for ioc in iocs]

        rule["logsource"] = {
            "category": "dns",
        }
        rule["detection"] = {
            "selection": {
                "query|contains": domains,
            },
            "condition": "selection",
        }

        return yaml.dump(rule, default_flow_style=False, allow_unicode=True, sort_keys=False)


# Singleton
sigma_service = SigmaService()
