"""Servizio di generazione regole YARA.

Genera regole YARA da IoC estratti dall'analisi AI per il rilevamento
di malware e artefatti malevoli.
"""

from __future__ import annotations

import logging
import re
from datetime import datetime

from app.models.schemas import ArticleAnalyzed

logger = logging.getLogger(__name__)


def _sanitize_rule_name(name: str) -> str:
    """Crea un nome di regola YARA valido da una stringa arbitraria."""
    sanitized = re.sub(r"[^a-zA-Z0-9_]", "_", name)
    sanitized = re.sub(r"_+", "_", sanitized).strip("_")
    if sanitized and sanitized[0].isdigit():
        sanitized = "rule_" + sanitized
    return sanitized[:128] or "unnamed_rule"


class YARAService:
    """Genera regole YARA da articoli analizzati."""

    def generate_yara_rules(self, article: ArticleAnalyzed) -> str:
        """Genera regole YARA da un articolo analizzato."""
        if not article.analysis:
            return "// No analysis available for YARA rule generation"

        analysis = article.analysis
        rules = []

        # Rule per hash di malware
        hash_iocs = [
            ioc for ioc in analysis.indicators
            if ioc.type in ("hash_md5", "hash_sha1", "hash_sha256")
        ]
        if hash_iocs:
            rules.append(self._generate_hash_rule(article, hash_iocs))

        # Rule per ogni malware family
        for family in analysis.malware_families:
            network_iocs = [
                ioc for ioc in analysis.indicators
                if ioc.type in ("domain", "ip", "ipv4", "url")
            ]
            string_iocs = [
                ioc for ioc in analysis.indicators
                if ioc.type in ("filename",)
            ]
            if network_iocs or string_iocs:
                rules.append(
                    self._generate_malware_rule(article, family, network_iocs, string_iocs)
                )

        # Rule generica se non ci sono specifiche
        if not rules:
            generic_iocs = [
                ioc for ioc in analysis.indicators
                if ioc.type in ("domain", "ip", "ipv4", "url", "filename")
            ]
            if generic_iocs:
                rules.append(self._generate_generic_rule(article, generic_iocs))

        if not rules:
            return f"// No IoCs suitable for YARA rule generation from: {article.title}"

        header = self._generate_header(article)
        return header + "\n\n".join(rules)

    def _generate_header(self, article: ArticleAnalyzed) -> str:
        """Genera l'header del file YARA."""
        return (
            f"// YARA Rules generated by CTI Feed RSS Analyzer\n"
            f"// Source: {article.title}\n"
            f"// Date: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}\n"
            f"// Article ID: {article.id}\n\n"
            f"import \"hash\"\n\n"
        )

    def _generate_hash_rule(self, article: ArticleAnalyzed, hash_iocs: list) -> str:
        """Genera una regola YARA basata su hash."""
        analysis = article.analysis
        title = _sanitize_rule_name(article.title[:60])
        rule_name = f"hash_{title}"

        meta = self._build_meta(article)
        conditions = []

        for ioc in hash_iocs:
            val = ioc.value.lower()
            if ioc.type == "hash_md5" and len(val) == 32:
                conditions.append(f'hash.md5(0, filesize) == "{val}"')
            elif ioc.type == "hash_sha1" and len(val) == 40:
                conditions.append(f'hash.sha1(0, filesize) == "{val}"')
            elif ioc.type == "hash_sha256" and len(val) == 64:
                conditions.append(f'hash.sha256(0, filesize) == "{val}"')

        if not conditions:
            return ""

        condition_str = " or\n        ".join(conditions)

        return (
            f"rule {rule_name}\n"
            f"{{\n"
            f"{meta}"
            f"    condition:\n"
            f"        {condition_str}\n"
            f"}}\n"
        )

    def _generate_malware_rule(
        self, article: ArticleAnalyzed, family: str, network_iocs: list, string_iocs: list
    ) -> str:
        """Genera una regola YARA per una famiglia di malware."""
        rule_name = _sanitize_rule_name(f"malware_{family}")
        meta = self._build_meta(article, malware_family=family)

        strings = []
        idx = 0
        for ioc in network_iocs:
            idx += 1
            escaped = ioc.value.replace("\\", "\\\\").replace('"', '\\"')
            strings.append(f'        $net{idx} = "{escaped}" ascii wide nocase')

        for ioc in string_iocs:
            idx += 1
            escaped = ioc.value.replace("\\", "\\\\").replace('"', '\\"')
            strings.append(f'        $str{idx} = "{escaped}" ascii wide nocase')

        if not strings:
            return ""

        strings_block = "\n".join(strings)
        return (
            f"rule {rule_name}\n"
            f"{{\n"
            f"{meta}"
            f"    strings:\n"
            f"{strings_block}\n\n"
            f"    condition:\n"
            f"        any of them\n"
            f"}}\n"
        )

    def _generate_generic_rule(self, article: ArticleAnalyzed, iocs: list) -> str:
        """Genera una regola YARA generica da IoC."""
        title = _sanitize_rule_name(article.title[:60])
        rule_name = f"ioc_{title}"
        meta = self._build_meta(article)

        strings = []
        for i, ioc in enumerate(iocs[:50], 1):
            escaped = ioc.value.replace("\\", "\\\\").replace('"', '\\"')
            strings.append(f'        $ioc{i} = "{escaped}" ascii wide nocase')

        strings_block = "\n".join(strings)
        return (
            f"rule {rule_name}\n"
            f"{{\n"
            f"{meta}"
            f"    strings:\n"
            f"{strings_block}\n\n"
            f"    condition:\n"
            f"        any of them\n"
            f"}}\n"
        )

    def _build_meta(self, article: ArticleAnalyzed, malware_family: str = "") -> str:
        """Genera il blocco meta di una regola YARA."""
        analysis = article.analysis
        lines = [
            f'        author = "CTI Feed RSS Analyzer"',
            f'        description = "{article.title[:200].replace(chr(34), chr(39))}"',
            f'        date = "{datetime.utcnow().strftime("%Y-%m-%d")}"',
            f'        reference = "{article.link}"',
        ]
        if analysis:
            lines.append(f'        severity = "{analysis.severity.value}"')
            lines.append(f'        category = "{analysis.threat_category.value}"')
        if malware_family:
            lines.append(f'        malware_family = "{malware_family}"')
        if analysis and analysis.threat_actors:
            actors = ", ".join(ta.name for ta in analysis.threat_actors[:5])
            lines.append(f'        threat_actors = "{actors}"')

        return "    meta:\n" + "\n".join(lines) + "\n\n"


# Singleton
yara_service = YARAService()
